<?php

/**
 * Implements hook_cron().
 */
function sports_cron() {
  // With this approach, each cron run has to run the query to check if there are
  // any teams without players and then delete them. If the cron runs often, most
  // of the times there will be nothing to delete and we run this query for no reason.
  // Perhaps a better way is using a queue:
  // @see TeamCleanerWorker
  $database = \Drupal::database();
  $result = $database->query("SELECT id FROM {teams} WHERE id NOT IN (SELECT team_id FROM {players} WHERE team_id IS NOT NULL)")->fetchAllAssoc('id');
  if (!$result) {
    return;
  }

  $ids = array_keys($result);
  $database->delete('teams')
    ->condition('id', $ids, 'IN')
    ->execute();
}

/**
 * Implements hook_views_data().
 */
function sports_views_data() {
  $data = [];

  // Players table
  $data['players'] = [];
  $data['players']['table']['group'] = t('Sports');
  $data['players']['table']['base'] = array(
    'field' => 'id',
    'title' => t('Players'),
    'help' => t('Holds player data.'),
  );

  // Players fields
  $data['players']['id'] = array(
    'title' => t('ID'),
    'help' => t('The unique player ID.'),
    'field' => array(
      'id' => 'numeric',
    ),
  );

  return $data;
}