<?php

/**
 * Implements hook_cron().
 */
function sports_cron() {
  // With this approach, each cron run has to run the query to check if there are
  // any teams without players and then delete them. If the cron runs often, most
  // of the times there will be nothing to delete and we run this query for no reason.
  // Perhaps a better way is using a queue:
  // @see TeamCleanerWorker
  $database = \Drupal::database();
  $result = $database->query("SELECT id FROM {teams} WHERE id NOT IN (SELECT team_id FROM {players} WHERE team_id IS NOT NULL)")->fetchAllAssoc('id');
  if (!$result) {
    return;
  }

  $ids = array_keys($result);
  $database->delete('teams')
    ->condition('id', $ids, 'IN')
    ->execute();
}

/**
 * Implements hook_views_data().
 */
function sports_views_data() {
  $data = [];

  // Players table
  $data['players'] = [];
  $data['players']['table']['group'] = t('Sports');
  $data['players']['table']['base'] = array(
    'field' => 'id',
    'title' => t('Players'),
    'help' => t('Holds player data.'),
  );

  // Players fields
  $data['players']['id'] = array(
    'title' => t('ID'),
    'help' => t('The unique player ID.'),
    'field' => array(
      'id' => 'numeric',
    ),
  );

  $data['players']['name'] = array(
    'title' => t('Name'),
    'help' => t('The name of the player.'),
    'field' => array(
      'id' => 'standard',
    ),
  );

  $data['players']['data'] = array(
    'title' => t('Data'),
    'help' => t('The player data.'),
    'field' => array(
      'id' => 'serialized',
    ),
  );

  $data['players']['team_id'] = array(
    'title' => t('Team ID'),
    'help' => t('The unique team ID of the player.'),
    'field' => array(
      'id' => 'numeric',
    ),
    'relationship' => array(
      'base' => 'teams',
      'base field' => 'id',
      'id' => 'standard',
      'label' => t('Player team'),
    ),
    'argument' => array(
      'id' => 'numeric',
    ),
  );

  // Teams table
  $data['teams'] = [];
  $data['teams']['table']['group'] = t('Sports');

  // Teams fields
  $data['teams']['name'] = array(
    'title' => t('Name'),
    'help' => t('The name of the team.'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'team_filter',
    ),
  );

  $data['teams']['description'] = array(
    'title' => t('Description'),
    'help' => t('The description of the team.'),
    'field' => array(
      'id' => 'standard',
    ),
  );

  $data['teams']['team'] = array(
    'title' => t('Team'),
    'help' => t('The team (either an ID or a team name).'),
    'argument' => array(
      'id' => 'team',
    ),
  );

  return $data;
}
